<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BusinessTypeSeeder extends Seeder
{
    public function run()
    {
        ini_set('memory_limit', '-1');

        DB::statement("INSERT INTO `business_types` (`id`, `business_id`, `type`) VALUES
            (1, '1', 'Auto Accessories'),
            (2, '1', 'Auto Dealers – New'),
            (3, '1', 'Auto Dealers – Used'),
            (4, '1', 'Detail & Carwash'),
            (5, '1', 'Gas Stations'),
            (6, '1', 'Motorcycle Sales & Repair'),
            (7, '1', 'Rental & Leasing'),
            (8, '1', 'Service, Repair & Parts'),
            (9, '1', 'Towing'),
            (10, '2', 'Consultants'),
            (11, '2', 'Employment Agency'),
            (12, '2', 'Marketing & Communications'),
            (13, '2', 'Office Supplies'),
            (14, '2', 'Printing & Publishing'),
            (15, '3', 'Computer Programming & Support'),
            (16, '3', 'Consumer Electronics & Accessories '),
            (17, '4', 'Architects, Landscape Architects, Engineers & Surveyors'),
            (18, '4', 'Blasting & Demolition'),
            (19, '4', 'Building Materials & Supplies'),
            (20, '4', 'Construction Companies'),
            (21, '4', 'Electricians'),
            (22, '4', 'Engineer, Survey'),
            (23, '4', 'Environmental Assessments'),
            (24, '4', 'Inspectors'),
            (25, '4', 'Plaster & Concrete'),
            (26, '4', 'Plumbers'),
            (27, '4', 'Roofers '),
            (28, '5', 'Adult & Continuing Education'),
            (29, '5', 'Early Childhood Education'),
            (30, '5', 'Educational Resources'),
            (31, '5', 'Other Educational'),
            (32, '6', 'Artists, Writers'),
            (33, '6', 'Event Planners & Supplies'),
            (34, '6', 'Golf Courses'),
            (35, '6', 'Movies'),
            (36, '6', 'Productions'),
            (37, '7', 'Desserts, Catering & Supplies'),
            (38, '7', 'Fast Food & Carry Out'),
            (39, '7', 'Grocery, Beverage & Tobacco'),
            (40, '7', 'Restaurants'),
            (41, '8', 'Acupuncture'),
            (42, '8', 'Assisted Living & Home Health Care'),
            (43, '8', 'Audiologist'),
            (44, '8', 'Chiropractic'),
            (45, '8', 'Clinics & Medical Centers'),
            (46, '8', 'Dental'),
            (47, '8', 'Diet I& Nutrition'),
            (48, '8', 'Laboratory, Imaging & Diagnostic'),
            (49, '8', 'Massage Therapy'),
            (50, '8', 'Mental Health'),
            (51, '8', 'Nurse'),
            (52, '8', 'Optical'),
            (53, '8', 'Pharmacy, Drug & Vitamin Stores'),
            (54, '8', 'Physical Therapy'),
            (55, '8', 'Physicians & Assistants'),
            (56, '8', 'Podiatry'),
            (57, '8', 'Social Worker'),
            (58, '8', 'Animal Hospital'),
            (59, '8', 'Veterinary & Animal Surgeons'),
            (60, '9', 'Antiques & Collectibles'),
            (61, '9', 'Cleaning'),
            (62, '9', 'Crafts, Hobbies & Sports'),
            (63, '9', 'Flower Shops'),
            (64, '9', 'Home Furnishings'),
            (65, '9', 'Home Goods'),
            (66, '9', 'Home Improvements & Repairs'),
            (67, '9', 'Landscape & Lawn Service'),
            (68, '9', 'Pest Control'),
            (69, '9', 'Pool Supplies & Service'),
            (70, '9', 'Security System & Services'),
            (71, '10', 'Accountants'),
            (72, '10', 'Attorneys'),
            (73, '10', 'Financial Institutions'),
            (74, '10', 'Financial Services'),
            (75, '10', 'Insurance'),
            (76, '10', 'Other Legal'),
            (77, '11', 'Distribution, Import/Export'),
            (78, '11', 'Manufacturing'),
            (79, '11', 'Wholesale'),
            (80, '12', 'Cards & Gifts'),
            (81, '12', 'Clothing & Accessories'),
            (82, '12', 'Department Stores, Sporting Goods'),
            (83, '12', 'General'),
            (84, '12', 'Jewelry'),
            (85, '12', 'Shoes'),
            (86, '13', 'Civic Groups'),
            (87, '13', 'Funeral Service Providers & Cemetaries'),
            (88, '13', 'Miscellaneous'),
            (89, '13', 'Utility Companies'),
            (90, '14', 'Animal Care & Supplies'),
            (91, '14', 'Barber & Beauty Salons'),
            (92, '14', 'Beauty Supplies'),
            (93, '14', 'Dry Cleaners & Laundromats'),
            (94, '14', 'Exercise & Fitness'),
            (95, '14', 'Massage & Body Works'),
            (96, '14', 'Nail Salons'),
            (97, '14', 'Shoe Repairs'),
            (98, '14', 'Tailors'),
            (99, '15', 'Agencies & Brokerage'),
            (100, '15', 'Agents & Brokers'),
            (101, '15', 'Apartment & Home Rental'),
            (102, '15', 'Mortgage Broker & Lender'),
            (103, '15', 'Property Management'),
            (104, '15', 'Title Company '),
            (105, '16', 'Hotel, Motel & Extended Stay'),
            (106, '16', 'Moving & Storage'),
            (107, '16', 'Packaging & Shipping'),
            (108, '16', 'Transportation'),
            (109, '16', 'Travel & Tourism');"
        );

        DB::statement("UPDATE `business_types` SET `created_at`=now(),`updated_at`=now(); ");
    }
}
